name: Deploy to AWS Lambda

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install serverless framework
        run: npm install -g serverless

      - name: Install project dependencies
        run: pip install -r requirements.txt

      - name: Deploy to AWS Lambda
        env:
          AWS_ACCESS_KEY_ID: ${{ aws.AWS_CLIENT_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ aws.AWS_CLIENT_SECRET }}
        run: serverless deploy
